name: flutter_application_1
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_bloc: ^7.0.0
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

  flutter_native_splash: ^1.1.8+4

flutter_native_splash:
  color: "#FFFAFA"
  # background_image: "assets/splashScreen/splashLower.png"
  image: assets/splashScreen/splashLogo.png
  android: true
  ios: true
  fullscreen: true
  android_gravity: center
  # bottom, center,center_horizontal,
  # center_vertical, clip_horizontal,
  # clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top

flutter_icons:
  android: true
  ios: true
  image_path: "assets/appIcon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: cairo
      fonts:
        - asset: fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: fonts/Cairo-Light.ttf
          weight: 300
        - asset: fonts/Cairo-Regular.ttf
          weight: 400
        - asset: fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: fonts/Cairo-Bold.ttf
          weight: 700
        - asset: fonts/Cairo-Black.ttf
          weight: 900
